### ISSUE TITLE
DE_load_old vs. DE_load_new

### ISSUE THREAD

**Issue by uvchik** [Open-Power-System-Data/time_series#20]
What is the difference between `DE_load_old` and` DE_load_new`? In the documentation both are the "Total load in Germany in MW" but in 2015 the values are different.

**Comment by jgmill** [comment]
The data are from two different platforms, although both are maintained by ENTSO-E: `DE_load_old` is taken from the [ENTSO-E Data Portal](https://www.entsoe.eu/data/data-portal/consumption/Pages/default.aspx), which was discontinued in 2016 and replaced by the [ENTSO-E Power Statistics](https://www.entsoe.eu/data/statistics/Pages/default.aspx). `DE_load_new` is taken from the [ENTSO-E Transparency Platform](https://transparency.entsoe.eu/load-domain/r2/totalLoadR2/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&dateTime.dateTime=06.09.2017+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!CTY|10Y1001A1001A83F&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))

I had also noted that the reported values differ. In Germany in 2015, the load reported on the Data Portal is on avarage 3.1 GW or 5.5 % higher than that reported on the Transparency Platform, but this difference also changes every hour.

I am not sure where these differences are rooted, but my best guess is that the reason lies with the different reporting deadlines: Values on the Transparency Platform have to be reported "[At the latest H+1 after the end of the operating period](https://www.entsoe.eu/fileadmin/user_upload/_library/resources/Transparency/MoP%20Ref02%20-%20EMFIP-Detailed%20Data%20Descriptions%20V1R4-2014-02-24.pdf#page=11)". For the Data Portal/Power Statistics, the data seems to be published only after the end of every month, which might allow for more accurate metering. 

In priciple, the differences could also be an issue of different definitions of "load": The [definition](https://www.entsoe.eu/fileadmin/user_upload/_library/resources/Transparency/MoP%20Ref02%20-%20EMFIP-Detailed%20Data%20Descriptions%20V1R4-2014-02-24.pdf#page=11) applied on the The ENTSO-E Transparency Platform is as follows (while I believe that the Data Portal/Power Statistics use the same definition, this is not 100% clear):
- The sum of power generated by plants on both TSO/DSO networks, from which is deducted
    - the balance (export -import) of exchanges on interconnections between neighbouring bidding zones. 
    - the power absorbed by energy storage resources.

The [ENTSO-E Glossary](https://www.entsoe.eu/data/data-portal/glossary/Pages/home.aspx?Filtername=doc%5Fterm&FilterMultiValue=*load*) also has this definition:
- The consumption corresponding to the short-term average active power absorbed by all installations connected to the transmission grid or to the distribution grid 
  - excluding consumption for pumping of the pumped-storage stations
  - excluding consumption of power plants auxiliaries
  - including network losses.

European electricity consumption data is a tricky subject, and neither of the hourly resolution time series are totally accurate. If you want to dig deeper: A former colleague did a [comparison of different sources](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2715986) a while ago, not yet including the ENTSO-E Transparency Platform however.

As a final note: The documentation to the [Agorameter](https://www.agora-energiewende.de/en/topics/-agothem-/Produkt/produkt/76/Agorameter/) estimates that the load values from the ENTSO-E Transparency Platform underestimate the actual situation on average by [8799.8 MW in 2017](https://www.agora-energiewende.de/fileadmin/Projekte/Agorameter/Hintergrunddokumentation_Agorameter_v20_web_EN.pdf#page=18).

**Comment by uvchik** [comment]
Thank you very much for this detailed answer.

**Comment by jgmill** [comment]
Please note that I have changed the notation of the load columns since version `2018-03-13` of the time series data package:
`DE_load_old` has become `DE_load_actual_entsoe_power_statistics`
`DE_load_new` has become `DE_load_actual_entsoe_transparency`

As of Version `2015-05-15`, The Data Portal/Power Statistics column is scaled with the country specific [coverage ratio](https://eepublicdownloads.blob.core.windows.net/public-cdn-container/clean-documents/Publications/Statistics/MS_guidelines2016.pdf#page=4).

**Comment by jgmill** [comment]
ENTSO-E had discontinued the [Power Statistics](https://www.entsoe.eu/data/power-stats/) in November 2019. An archive of historical data is now available, with the latest hourly load values provided for 31.10.2019.
